---
title: "assignment4final"
author: "Nathan Mokhtarzadeh"
date: "April 26, 2018"
output:
  word_document: default
  pdf_document: 
    latex_engine: xelatex
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(tidyverse)
library(foreign)
library(dplyr)
library(xtable)
library(reshape2)
library(stringr)

```


12.6.1

```{r}
who1 <- who %>%
  gather(new_sp_m014:newrel_f65, key = "key", value = "cases", na.rm = TRUE)
#who1
who1 %>%
  count(key)
who2 <- who1 %>% 
  mutate(key = stringr::str_replace(key, "newrel", "new_rel"))
who2



```
#1
#I think it's reasonable, but it could have some bad effects depending on what you want
#an NA value can prevent certain computations from being made while having a zero
#may result in some inaccurate computations like means

#2
#If you neglect the step we won't be able to separate into var, sexage, and new

```{r}
who3 <- who2 %>% 
  separate(key, c("new", "type", "sexage"), sep = "_")
#who3

who3 %>% 
  count(new)

who4 <- who3 %>% 
  select(-new, -iso2, -iso3)

who5 <- who4 %>% 
  separate(sexage, c("sex", "age"), sep = 1)
who5
```

##Problem 5
```{r}
annoying <- tibble(
  `1` = 1:10,
  `2` = `1` * 2 + rnorm(length(`1`))
)
annoying$`1`[1]
#4.2
plot(annoying)
#points(annoying[2], col = 'blue')
#points(annoying[1], col = 'red')
#4.3
toAdd <- annoying[[1]]/annoying[[2]]
annoying <- add_column(annoying,`3` = toAdd)
#4.4
names(annoying)[names(annoying) == '3'] <- 'three'
names(annoying)[names(annoying) == '2'] <- 'two'
names(annoying)[names(annoying) == '1'] <- 'one'

#5 using data from previous questions
#run in script file, the data displays there
tibble::enframe(annoying[1:3,])
```


##Table 4->6
```{r}
pew <- read.spss('pew.sav')
pewDf <- as_data_frame(pew)

religion <- pewDf[c('q16', 'reltrad', 'income')]
religion$reltrad <- as.character(religion$reltrad)
religion$reltrad <- str_replace(religion$reltrad, 'Churches', "")
religion$reltrad <- str_replace(religion$reltrad, 'Protestant', 'Prot')
religion$reltrad[religion$q16 == 'Atheist(do not believe in God)'] <- 'Atheist'
religion$reltrad[religion$q16 == 'Agnostic (not sure if there is a God)'] <- 'Agnostic'
religion$reltrad <- str_trim(religion$reltrad)
religion$reltrad <- str_replace_all(religion$reltrad, ' \\(.*?\\)', '')

religion$income <- c('Less than $10,000' = '<$10k', 
                     '10 to under $20,000' = '$10-20k', 
                     '20 to under $30,000' = '$20-30k', 
                     '30 to under $40,000' = '$30-40k', 
                     '40 to under $50,000' = '$40-50k', 
                     '50 to under $75,000' = '$50-75k',
                     '75 to under $100,000' = '$75-100k', 
                     '100 to under $150,000' = '$100-150k', 
                     '$150,000 or more' = '>150k', 
                     "Don't know/Refused (VOL)" = "Don't know/refused")[religion$income]

lens <- dplyr::count(religion, 'reltrad', 'income')
names(lens)[1] <- 'religion'

first <- religion %>%
  dplyr::group_by(reltrad, q16, income) %>%
  count(income)

second <- first[c('reltrad', 'income', 'n')]
third <- second %>% 
  dplyr::rename(freq = n)
#just showing the first ten elements, for whatever reason when I knit the entire dataset gets put onto the document and it becomes 300 pages
third[1:10,]

```


##Table 7 -> 8
```{r}
bb <- read.csv('billboard.csv')

clean <- bb %>% 
  gather(key = 'week', value = 'rank',  -time, -genre, -date.entered, -date.peaked, -year, -artist.inverted, -track) %>% 
  select(year, artist=artist.inverted, time, track, date = date.entered, week, rank ) %>% 
  filter(!is.na(rank)) %>% 
  arrange(track) %>% 
  separate(week, into=c('x', 'y', 'z'), convert = TRUE, sep=c(1, -7)) %>% 
  dplyr::rename(week = y) %>% 
  select(-x, -z) %>% 
  arrange(artist, track)
#When I knit, it shows the entire tibble data, just showing the first ten elements.
clean[1:10,]
```


